language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-lib' ]; then cd .. && eval "mv $currentfolder generator-node-lib" && cd generator-node-lib; fi
